apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: focus-hub
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.13.2
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 9600 # Puerto de monitoreo de Logstash
            initialDelaySeconds: 30 # Logstash tarda un poco en iniciar
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: logstash-config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-config-volume
          configMap:
            name: logstash-config

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: focus-hub
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
