services:
  frontend:
    image: pholcast25/focus-hub-frontend:latest  # Usando la imagen del frontend subida a Docker Hub
    command: npm run start
    volumes:
      - ./FocusHub-app:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: pholcast25/focus-hub-backend:latest  # Usando la imagen del backend subida a Docker Hub
    command: npm run start:dev
    volumes:
      - ./focus-hub-backend:/app
    ports:
      - "3000:3000"
