services:
  # --- Servicios de la Aplicación ---
  frontend:
    build:
      context: ./FocusHub-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./FocusHub-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - focus_hub_network

  backend:
    build:
      context: ./focus-hub-backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5000
    volumes:
      - ./focus-hub-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      logstash:
          condition: service_healthy
      mysql_db:
        condition: service_started
    networks:
      - focus_hub_network

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=focus_hub_database
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - focus_hub_network

  # --- Servicios ELK Stack ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - focus_hub_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    
    networks:
      - focus_hub_network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - focus_hub_network

volumes:
  mysql_data:
  esdata:

networks:
  focus_hub_network:
