services:
  frontend:
      #build:
        #context: ./FocusHub-app
        #dockerfile: Dockerfile
      image: pholcast25/focus-hub-angular:latest  # Imagen para Docker Hub
      ports:
        - "4200:4200"
      volumes:
        - ./FocusHub-app:/app
        #- /app/node_modules
      command: npm run start
      environment:
        - NODE_ENV=development
      depends_on:
        - backend

  backend:
    #build:
      #context: ./focus-hub-backend  # Directorio donde se encuentra el Dockerfile del backend
      #dockerfile: Dockerfile
    image: pholcast25/focus-hub-nest-js:latest
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      #- ./src:/usr/src/app/src
      - ./focus-hub-backend:/usr/src/app
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=focus_hub_database
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
